name: nuxt-sentry - publish version

on:
  push:
    branches:
      - master
      - release/**
    paths:
      - 'src/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.github/workflows/publish.yml'

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: npm
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm packages
        run: pnpm install -r --frozen-lockfile

      - name: Prepare Environment
        run: pnpm run dev:prepare

      - name: Pre-Pack
        run: pnpm run prepack

      - name: Publish
        run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
